### PR TITLE
Adds GitHub Action Workflow to create executables and auto-Release

### LINKED ISSUE #12: Use Github Actions for packaging
Work to use Github Actions to automate some of the busywork around automated testing and packaging of new releases.

### PR DESCRIPTION
**Pull request by JamzTheMan**
Creates windows executable and uploads artifact to auto-generated GitHub Release using commit message and tag.

Usage:
```
git tag v1.0.0-beta
git push origin feature/add-actions-release --tags
```

Fixes #12

### CODE REVIEW

**Comment by JamzTheMan** [comment]
Added in MacOS build. I was able to download and run it on my M1 MacBook (after unlocking it in file vault of course)
Seemed to work ok!

Linux version needs work.

**Comment by emersonrp** [comment]
I am a little slammed IRL at the moment but I am very excited about this and will pay attention to it Real Soon Now.  Thanks!

**Comment by emersonrp** [comment]
Merged this today, finally.  The build run failed:

https://github.com/emersonrp/bindcontrol/actions/runs/8455181583/job/23162035501

Dunno if you can see that without being me;  my knowledge of actions is still shamefully lacking.  Anyway, if complained about the `Run commitMessage=$(git log -1 --pretty=format:%B)` step:

```
Error: Unable to process file command 'env' successfully.
Error: Invalid format 'Adds GitHub Action Workflow to create executables and auto-Release'
```

Not sure what it's cranky about, any thoughts?

Thanks again for doing this, it's going to be a game-changer for me.

**Comment by emersonrp** [comment]
Just adding here so that you'll see -- just released 0.14.1, and the build action worked flawlessly (a couple of warnings about deprecations but I'll look into those).  So, the March failure seems to have been fixed on their end, might just have been some transient weirdness.  This is, as I said, a game-changer, thank you again.

**Comment by JamzTheMan** [comment]
Sorry, been slammed with work so missed the previous message but glad it worked for the latest release! Feel free to @mention me if it breaks, glad to help!

**Comment by emersonrp** [comment]
It's actually been working a treat -- I've gotten a little more up to speed on tinkering with actions, and I have it acting just the way I want to now for the Windows and MacOS builds.  It's been really great and I continue to appreciate how much easier it's made life.  Thanks again, will keep you posted if anything comes up yes.

Ooh FWIW I discovered the 'env' problem I had up above happened when there was a multi-line commit message.  I tinkered and Googled a bit and found out how to make it work with those, and so now my process consists of doing a last merge commit of the thing I'm releasing, doing the release notes as the commit message of that, and then tagging and pushing.  POW done.  :)

**Pull request merged**
